sudo: required
services:
  - docker

before_install:
  - docker build -t vrushab/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vrushab/react-test npm test -- --coverage

after_success:
  - docker build -t vrushab/multi-client ./client
  - docker build -t vrushab/multi-nginx ./nginx
  - docker build -t vrushab/multi-server ./server
  - docker build -t vrushab/multi-worker ./worker
