sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: python
python:
  - "3.9"
before_install:
  - openssl aes-256-cbc -K $encrypted_6afc8162126b_key -iv $encrypted_6afc8162126b_iv -in multi-k8s-424303-4a18ada1f4a9.json.enc -out multi-k8s-424303-4a18ada1f4a9.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-424303-4a18ada1f4a9.json
  - gcloud config set project multi-k8s-424303
  - gcloud config set compute/zone us-west1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t vrushab97/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vrushab97/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
