sudo: required
services:
  - docker

before_install:
  - docker build -t vrushab/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vrushab/react-test npm test -- --coverage

after_success:
  - docker build -t vrushab/multi-client ./client
  - docker build -t vrushab/multi-nginx ./nginx
  - docker build -t vrushab/multi-server ./server
  - docker build -t vrushab/multi-worker ./worker
  # login and push images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"--password-stdin
  - docker push vrushab/multi-client
  - docker push vrushab/multi-nginx
  - docker push vrushab/multi-server
  - docker push vrushab/multi-worker
